dev:
  restart: always
  image: oppara/centos6-php56
  ports:
    - "80:80"
    - "443:443"
  links:
    - db_app
    - db_app_test
  volumes:
    - ./src:/var/www/html
  entrypoint: /etc/services.sh

db_app:
  image: postgres:9.5
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: app
    LC_ALL: C

db_app_test:
  image: postgres:9.5
  environment:
    POSTGRES_USER: vagrant
    POSTGRES_PASSWORD: pass
    POSTGRES_DB: app_test
    LC_ALL: C
